"""Scientific workflows with a lazy backward-compatible public API.

Importing one workflow submodule must not import every modelling workflow.
Public names formerly re-exported here are resolved only when requested.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_PUBLIC_API: dict[str, tuple[str, str]] = {
    "add_pca_relative_quality_flags": ("src.workflows.pca_selection", "add_pca_relative_quality_flags"),
    "add_robust_spectral_qc": ("src.workflows.quality_check", "add_robust_spectral_qc"),
    "add_selection_track": ("src.workflows.simca_candidates", "add_selection_track"),
    "add_simca_candidate_ids": ("src.workflows.simca_candidates", "add_simca_candidate_ids"),
    "add_simca_robustness_scores": ("src.workflows.simca_robustness", "add_simca_robustness_scores"),
    "aggregate_grid_metrics": ("src.workflows.simca_grid_evaluation", "aggregate_grid_metrics"),
    "aggregate_pca_preprocessing_diagnostics": ("src.workflows.pca_selection", "aggregate_pca_preprocessing_diagnostics"),
    "allowed_pca_preprocessing_pairs": ("src.workflows.simca_candidates", "allowed_pca_preprocessing_pairs"),
    "apply_flag_pareto_filter_by_track": ("src.workflows.simca_final_selection", "apply_flag_pareto_filter_by_track"),
    "apply_metric_pareto_filter_by_track": ("src.workflows.simca_final_selection", "apply_metric_pareto_filter_by_track"),
    "apply_pca_artifact_review_decisions": ("src.workflows.pca_selection", "apply_pca_artifact_review_decisions"),
    "apply_rate_threshold_filter_by_track": ("src.workflows.simca_final_selection", "apply_rate_threshold_filter_by_track"),
    "assert_no_split_leakage": ("src.workflows.protocol_split", "assert_no_split_leakage"),
    "assert_no_test_stage_inputs": ("src.workflows.protocol_audit", "assert_no_test_stage_inputs"),
    "assert_wavelength_lock": ("src.workflows.matrix_preprocessing", "assert_wavelength_lock"),
    "assign_pareto_tiers": ("src.workflows.simca_final_selection", "assign_pareto_tiers"),
    "audit_simca_candidate_technical_status": ("src.workflows.simca_candidates", "audit_simca_candidate_technical_status"),
    "balanced_strategy_grid_for_matrix": ("src.workflows.simca", "balanced_strategy_grid_for_matrix"),
    "best_completed_trial_row": ("src.workflows.simca_optuna", "best_completed_trial_row"),
    "binary_class_separation_scores": ("src.workflows.pca", "binary_class_separation_scores"),
    "build_2way_object_image_diagnostics": ("src.workflows.simca_pure_test", "build_2way_object_image_diagnostics"),
    "build_2way_object_metrics": ("src.workflows.simca_pure_test", "build_2way_object_metrics"),
    "build_2way_pixel_image_diagnostics": ("src.workflows.simca_pure_test", "build_2way_pixel_image_diagnostics"),
    "build_2way_pixel_metrics": ("src.workflows.simca_pure_test", "build_2way_pixel_metrics"),
    "build_3way_outputs": ("src.workflows.simca_pure_test", "build_3way_outputs"),
    "build_ablation_diagnostics": ("src.workflows.simca_robustness", "build_ablation_diagnostics"),
    "build_border_core_diagnostics": ("src.workflows.simca_robustness", "build_border_core_diagnostics"),
    "build_border_core_skip_table": ("src.workflows.simca_robustness", "build_border_core_skip_table"),
    "build_evaluable_model_universe": ("src.workflows.simca_budgeted_search_audit", "build_evaluable_model_universe"),
    "build_configuration_catalog": ("src.workflows.simca_grid_evaluation", "build_configuration_catalog"),
    "build_duplicate_groups": ("src.workflows.simca_grid_evaluation", "build_duplicate_groups"),
    "build_duplicated_candidate_review": ("src.workflows.simca_robustness", "build_duplicated_candidate_review"),
    "build_final_selection_guardrails": ("src.workflows.simca_final_selection", "build_final_selection_guardrails"),
    "build_final_selection_pool": ("src.workflows.simca_final_selection", "build_final_selection_pool"),
    "build_final_selection_protocol": ("src.workflows.simca_final_selection", "build_final_selection_protocol"),
    "build_grouped_folds": ("src.workflows.protocol_split", "build_grouped_folds"),
    "build_image_qc_table": ("src.workflows.quality_check", "build_image_qc_table"),
    "build_image_qc_warnings": ("src.workflows.quality_check", "build_image_qc_warnings"),
    "build_locked_spatial_validation_outputs": ("src.workflows.spatial_postprocessing_calibration", "build_locked_spatial_validation_outputs"),
    "build_locked_validation_candidate_pool": ("src.workflows.simca_candidates", "build_locked_validation_candidate_pool"),
    "build_matrix_coverage_table": ("src.workflows.matrix_preprocessing", "build_matrix_coverage_table"),
    "build_mixture_guardrails": ("src.workflows.simca_mixture", "build_mixture_guardrails"),
    "build_mixture_projection_filters": ("src.workflows.simca_mixture", "build_mixture_projection_filters"),
    "build_mixture_protocol": ("src.workflows.simca_mixture", "build_mixture_protocol"),
    "build_object_qc_table": ("src.workflows.quality_check", "build_object_qc_table"),
    "build_object_qc_warnings": ("src.workflows.quality_check", "build_object_qc_warnings"),
    "build_object_shape_check_tables": ("src.workflows.quality_check", "build_object_shape_check_tables"),
    "build_optuna_pareto_candidates": ("src.workflows.simca_optuna", "build_optuna_pareto_candidates"),
    "build_optuna_search_efficiency_audit": ("src.workflows.simca_optuna", "build_optuna_search_efficiency_audit"),
    "build_optuna_search_plan_hash": ("src.workflows.simca_optuna", "build_optuna_search_plan_hash"),
    "build_optuna_study_registry": ("src.workflows.simca_optuna", "build_optuna_study_registry"),
    "build_pareto_diagnostics": ("src.workflows.simca_robustness", "build_pareto_diagnostics"),
    "build_pareto_reference": ("src.workflows.simca_grid_evaluation", "build_pareto_reference"),
    "build_pca_artifact_review_table": ("src.workflows.pca_selection", "build_pca_artifact_review_table"),
    "build_pca_candidate_plan": ("src.workflows.pca", "build_pca_candidate_plan"),
    "build_pca_preprocessing_configs_by_matrix_family": ("src.workflows.simca_candidates", "build_pca_preprocessing_configs_by_matrix_family"),
    "build_pca_run_fingerprint": ("src.workflows.pca_selection", "build_pca_run_fingerprint"),
    "build_pca_scoring_diagnostics": ("src.workflows.pca_selection", "build_pca_scoring_diagnostics"),
    "build_pca_selection_diagnostics": ("src.workflows.pca_selection", "build_pca_selection_diagnostics"),
    "build_pixel_vote_table": ("src.workflows.simca_calibration_thresholds", "build_pixel_vote_table"),
    "build_selected_model_reference": ("src.workflows.simca_selected_model_audit", "build_selected_model_reference"),
    "build_selected_run_fold_metrics": ("src.workflows.simca_selected_model_audit", "build_selected_run_fold_metrics"),
    "build_pca_selection_flow_tables": ("src.workflows.pca_selection", "build_pca_selection_flow_tables"),
    "build_preregistered_ablation_plan": ("src.workflows.simca_optuna", "build_preregistered_ablation_plan"),
    "build_protocol_manifest": ("src.workflows.matrix_preprocessing", "build_protocol_manifest"),
    "build_pure_test_guardrails": ("src.workflows.simca_pure_test", "build_pure_test_guardrails"),
    "build_pure_test_projection_filters": ("src.workflows.simca_pure_test", "build_pure_test_projection_filters"),
    "build_pure_test_protocol": ("src.workflows.simca_pure_test", "build_pure_test_protocol"),
    "build_qc_alerts_table": ("src.workflows.quality_check", "build_qc_alerts_table"),
    "build_qc_exclusion_report": ("src.workflows.quality_check", "build_qc_exclusion_report"),
    "build_qc_flags_table": ("src.workflows.quality_check", "build_qc_flags_table"),
    "build_qc_protocol": ("src.workflows.quality_check", "build_qc_protocol"),
    "build_qc_visual_review_report": ("src.workflows.quality_check", "build_qc_visual_review_report"),
    "build_random_state_stability_panel": ("src.workflows.simca_robustness", "build_random_state_stability_panel"),
    "build_schema_manifest": ("src.workflows.simca_tables", "build_schema_manifest"),
    "build_segmentation_diagnostics_table": ("src.workflows.quality_check", "build_segmentation_diagnostics_table"),
    "build_simca_output_signatures": ("src.workflows.simca_candidates", "build_simca_output_signatures"),
    "build_spectral_integrity_table": ("src.workflows.quality_check", "build_spectral_integrity_table"),
    "build_split_diagnostics": ("src.workflows.protocol_split", "build_split_diagnostics"),
    "build_track_scoring_table": ("src.workflows.simca_robustness", "build_track_scoring_table"),
    "build_validation_guardrails": ("src.workflows.simca_grid_evaluation", "build_validation_guardrails"),
    "build_wavelength_config": ("src.workflows.matrix_preprocessing", "build_wavelength_config"),
    "calibrate_simca_thresholds_cv": ("src.workflows.simca", "calibrate_simca_thresholds_cv"),
    "candidate_identity_payload": ("src.workflows.simca_candidates", "candidate_identity_payload"),
    "canonicalize_simca_columns": ("src.workflows.simca_tables", "canonicalize_simca_columns"),
    "check_missing_required_fields": ("src.workflows.quality_check", "check_missing_required_fields"),
    "choose_mixture_diagnostic_images": ("src.workflows.simca_mixture", "choose_mixture_diagnostic_images"),
    "close_optuna_study": ("src.workflows.simca_optuna", "close_optuna_study"),
    "compact_simca_table": ("src.workflows.simca_tables", "compact_simca_table"),
    "compact_simca_table_for_path": ("src.workflows.simca_tables", "compact_simca_table_for_path"),
    "compare_aligned_loadings": ("src.workflows.pca", "compare_aligned_loadings"),
    "compare_pca_representations": ("src.workflows.pca", "compare_pca_representations"),
    "compute_group_centroid_displacements": ("src.workflows.pca", "compute_group_centroid_displacements"),
    "compute_group_compactness": ("src.workflows.pca", "compute_group_compactness"),
    "compute_pca_summary_metrics": ("src.workflows.pca", "compute_pca_summary_metrics"),
    "concat_nonempty_tables": ("src.workflows.simca_tables", "concat_nonempty_tables"),
    "decode_boolean_map": ("src.workflows.spatial_postprocessing_calibration", "decode_boolean_map"),
    "deduplicate_metric_equivalent_simca_candidates": ("src.workflows.simca_candidates", "deduplicate_metric_equivalent_simca_candidates"),
    "deduplicate_simca_candidates": ("src.workflows.simca_candidates", "deduplicate_simca_candidates"),
    "deduplicate_simca_refit_configs": ("src.workflows.simca_candidates", "deduplicate_simca_refit_configs"),
    "DEFAULT_MIXTURE_EVALUATION_STAGE": ("src.workflows.simca_mixture", "DEFAULT_MIXTURE_EVALUATION_STAGE"),
    "DEFAULT_PCA_SELECTION_CONFIG": ("src.workflows.pca_selection", "DEFAULT_PCA_SELECTION_CONFIG"),
    "DEFAULT_PURE_TEST_EVALUATION_STAGE": ("src.workflows.simca_pure_test", "DEFAULT_PURE_TEST_EVALUATION_STAGE"),
    "drop_all_na_columns": ("src.workflows.simca_tables", "drop_all_na_columns"),
    "eligible_object_ids": ("src.workflows.protocol_split", "eligible_object_ids"),
    "encode_boolean_map": ("src.workflows.spatial_postprocessing_calibration", "encode_boolean_map"),
    "ensure_candidate_columns": ("src.workflows.simca_selection_utils", "ensure_candidate_columns"),
    "evaluate_balanced_sampling_grid": ("src.workflows.matrix_preprocessing", "evaluate_balanced_sampling_grid"),
    "evaluate_locked_oof_domain": ("src.workflows.simca_grid_evaluation", "evaluate_locked_oof_domain"),
    "evaluate_locked_validation_predictions": ("src.workflows.simca_grid_evaluation", "evaluate_locked_validation_predictions"),
    "evaluate_pca_stability": ("src.workflows.pca", "evaluate_pca_stability"),
    "evaluate_preprocessing_grid": ("src.workflows.matrix_preprocessing", "evaluate_preprocessing_grid"),
    "exact_int_list": ("src.workflows.simca_pure_test", "exact_int_list"),
    "extract_selected_crossfit_metrics": ("src.workflows.simca_selected_model_audit", "extract_selected_crossfit_metrics"),
    "fill_selected_config_defaults": ("src.workflows.simca_selection_utils", "fill_selected_config_defaults"),
    "filter_simca_candidates_by_pca_preprocessing": ("src.workflows.simca_candidates", "filter_simca_candidates_by_pca_preprocessing"),
    "finalize_grid_audit": ("src.workflows.simca_grid_evaluation", "finalize_grid_audit"),
    "finalize_simca_metric_table": ("src.workflows.simca_pure_test", "finalize_simca_metric_table"),
    "fit_final_simca_model": ("src.workflows.simca", "fit_final_simca_model"),
    "fit_one_class_simca": ("src.workflows.simca", "fit_one_class_simca"),
    "fit_pca_candidate": ("src.workflows.pca", "fit_pca_candidate"),
    "fit_simca_bundle_from_matrix": ("src.workflows.simca", "fit_simca_bundle_from_matrix"),
    "format_final_selection_reason": ("src.workflows.simca_final_selection", "format_final_selection_reason"),
    "format_pca_selection_reason": ("src.workflows.pca_selection", "format_pca_selection_reason"),
    "freeze_pca_shortlist": ("src.workflows.pca_selection", "freeze_pca_shortlist"),
    "hash_locked_validation_evaluation_rule": ("src.workflows.simca_candidates", "hash_locked_validation_evaluation_rule"),
    "hash_locked_validation_plan": ("src.workflows.simca_candidates", "hash_locked_validation_plan"),
    "hash_pca_input_artifacts": ("src.workflows.pca_selection", "hash_pca_input_artifacts"),
    "hash_pca_review_table": ("src.workflows.pca_selection", "hash_pca_review_table"),
    "infer_matrix_family": ("src.workflows.simca_candidates", "infer_matrix_family"),
    "infer_model_family_from_rule_token": ("src.workflows.simca_selection_utils", "infer_model_family_from_rule_token"),
    "iter_dataframe_batches": ("src.workflows.simca_tables", "iter_dataframe_batches"),
    "join_flags": ("src.workflows.simca_final_selection", "join_flags"),
    "load_existing_mixture_outputs": ("src.workflows.simca_mixture", "load_existing_mixture_outputs"),
    "load_existing_pure_test_outputs": ("src.workflows.simca_pure_test", "load_existing_pure_test_outputs"),
    "mahalanobis_centroid_distance": ("src.workflows.pca", "mahalanobis_centroid_distance"),
    "make_optuna_binary_pareto_objective": ("src.workflows.simca_optuna", "make_optuna_binary_pareto_objective"),
    "make_pca_selection_config": ("src.workflows.pca_selection", "make_pca_selection_config"),
    "make_simca_optuna_objective": ("src.workflows.simca_optuna", "make_simca_optuna_objective"),
    "make_target_train_filters": ("src.workflows.simca", "make_target_train_filters"),
    "merge_existing_reviews_or_initialize": ("src.workflows.quality_check", "merge_existing_reviews_or_initialize"),
    "missing_existing_mixture_paths": ("src.workflows.simca_mixture", "missing_existing_mixture_paths"),
    "missing_existing_pure_test_paths": ("src.workflows.simca_pure_test", "missing_existing_pure_test_paths"),
    "n_components_for_cumulative_variance": ("src.workflows.pca", "n_components_for_cumulative_variance"),
    "normalize_simca_candidate_columns": ("src.workflows.simca_candidates", "normalize_simca_candidate_columns"),
    "normalize_simca_rule_columns": ("src.workflows.simca_selection_utils", "normalize_simca_rule_columns"),
    "OBJECT_MATRIX_METHODS": ("src.workflows.pca", "OBJECT_MATRIX_METHODS"),
    "optuna_trials_dataframe": ("src.workflows.simca_optuna", "optuna_trials_dataframe"),
    "optuna_trials_to_candidate_configs": ("src.workflows.simca_optuna", "optuna_trials_to_candidate_configs"),
    "pareto_front": ("src.workflows.simca_selection_utils", "pareto_front"),
    "pareto_front_mask": ("src.workflows.simca_final_selection", "pareto_front_mask"),
    "pareto_objective_columns": ("src.workflows.simca_final_selection", "pareto_objective_columns"),
    "PCA_ARTIFACT_COLUMNS": ("src.experiment_config", "PCA_ARTIFACT_COLUMNS"),
    "pca_component_variance_table": ("src.workflows.pca", "pca_component_variance_table"),
    "pca_distance_summary": ("src.workflows.pca", "pca_distance_summary"),
    "pca_input_artifact_paths": ("src.workflows.pca_selection", "pca_input_artifact_paths"),
    "pca_input_fingerprint": ("src.workflows.pca_selection", "pca_input_fingerprint"),
    "pca_matrix_variant_from_method": ("src.workflows.pca", "pca_matrix_variant_from_method"),
    "PCA_TECHNICAL_FLAG_COLUMNS": (
        "src.experiment_config",
        "PCA_TECHNICAL_FLAG_COLUMNS",
    ),
    "PCASelectionConfig": ("src.workflows.pca_selection", "PCASelectionConfig"),
    "PCASelectionProfile": ("src.workflows.pca_selection", "PCASelectionProfile"),
    "PIXEL_MATRIX_METHODS": ("src.workflows.pca", "PIXEL_MATRIX_METHODS"),
    "pixel_object_score_metrics": ("src.workflows.pca", "pixel_object_score_metrics"),
    "predict_pixels_with_simca": ("src.workflows.simca", "predict_pixels_with_simca"),
    "prepare_mixture_outputs": ("src.workflows.simca_mixture", "prepare_mixture_outputs"),
    "prepare_simca_projection": ("src.workflows.simca", "prepare_simca_projection"),
    "project_pixels_with_rule_variants": ("src.workflows.simca", "project_pixels_with_rule_variants"),
    "project_simca_bundle": ("src.workflows.simca", "project_simca_bundle"),
    "qc_requires_new_cycle": ("src.workflows.quality_check", "qc_requires_new_cycle"),
    "read_simca_table": ("src.workflows.simca_tables", "read_simca_table"),
    "refit_best_grid_row": ("src.workflows.simca", "refit_best_grid_row"),
    "refit_empirical_cv_rule_row": ("src.workflows.simca", "refit_empirical_cv_rule_row"),
    "refit_optuna_best_trial": ("src.workflows.simca_optuna", "refit_optuna_best_trial"),
    "refit_selected_simca_configs": ("src.workflows.simca", "refit_selected_simca_configs"),
    "refit_selected_simca_row": ("src.workflows.simca", "refit_selected_simca_row"),
    "resolve_merge_suffix_columns": ("src.workflows.simca_tables", "resolve_merge_suffix_columns"),
    "restore_mixture_selected_configs": ("src.workflows.simca_mixture", "restore_mixture_selected_configs"),
    "run_exhaustive_locked_grid_evaluation": ("src.workflows.simca_grid_evaluation", "run_exhaustive_locked_grid_evaluation"),
    "run_categorical_tpe_coverage_benchmark": ("src.workflows.simca_budgeted_search_audit", "run_categorical_tpe_coverage_benchmark"),
    "run_locked_simca_validation_refit": ("src.workflows.simca", "run_locked_simca_validation_refit"),
    "run_locked_simca_validation_refit_checkpointed": ("src.workflows.simca", "run_locked_simca_validation_refit_checkpointed"),
    "run_mixture_application_batches": ("src.workflows.simca_mixture", "run_mixture_application_batches"),
    "run_optuna_simca_pixel_optimization": ("src.workflows.simca_optuna", "run_optuna_simca_pixel_optimization"),
    "run_pure_test_refit_batches": ("src.workflows.simca_pure_test", "run_pure_test_refit_batches"),
    "run_selected_simca_random_state_stability": ("src.workflows.simca", "run_selected_simca_random_state_stability"),
    "run_selected_simca_random_state_stability_full": ("src.workflows.simca", "run_selected_simca_random_state_stability_full"),
    "run_selected_model_reference_audit": ("src.workflows.simca_selected_model_audit", "run_selected_model_reference_audit"),
    "run_simca_pixel_projection_grid": ("src.workflows.simca", "run_simca_pixel_projection_grid"),
    "run_simca_rule_variant_grid": ("src.workflows.simca", "run_simca_rule_variant_grid"),
    "run_single_simca_pixel_projection": ("src.workflows.simca", "run_single_simca_pixel_projection"),
    "save_final_selection_outputs": ("src.workflows.simca_final_selection", "save_final_selection_outputs"),
    "save_mixture_outputs": ("src.workflows.simca_mixture", "save_mixture_outputs"),
    "save_pure_test_outputs": ("src.workflows.simca_pure_test", "save_pure_test_outputs"),
    "schema_diagnostics": ("src.workflows.simca_tables", "schema_diagnostics"),
    "select_final_models_by_track": ("src.workflows.simca_final_selection", "select_final_models_by_track"),
    "select_pca_pareto_front": ("src.workflows.pca_selection", "select_pca_pareto_front"),
    "select_pca_preprocessing_shortlist": ("src.workflows.pca_selection", "select_pca_preprocessing_shortlist"),
    "select_pure_test_candidate_panel": ("src.workflows.simca_pure_test", "select_pure_test_candidate_panel"),
    "select_top_models": ("src.workflows.simca_selection_utils", "select_top_models"),
    "select_top_with_diversity": ("src.workflows.simca_final_selection", "select_top_with_diversity"),
    "select_track_primary_or_available_metrics": ("src.workflows.simca_robustness", "select_track_primary_or_available_metrics"),
    "selection_track_from_parts": ("src.workflows.simca_candidates", "selection_track_from_parts"),
    "simca_candidate_key": ("src.workflows.simca_candidates", "simca_candidate_key"),
    "simca_metadata_columns": ("src.workflows.simca_pure_test", "simca_metadata_columns"),
    "SIMCA_RULE_METADATA": ("src.workflows.simca_selection_utils", "SIMCA_RULE_METADATA"),
    "SIMCA_TABLE_COLUMNS": ("src.workflows.simca_tables", "SIMCA_TABLE_COLUMNS"),
    "sort_detection_selection": ("src.workflows.simca_selection_utils", "sort_detection_selection"),
    "sort_simca_selection": ("src.workflows.simca_selection_utils", "sort_detection_selection"),
    "split_flag_string": ("src.workflows.simca_final_selection", "split_flag_string"),
    "stable_frame_signature": ("src.workflows.simca_candidates", "stable_frame_signature"),
    "standard_grid_sort": ("src.workflows.simca", "standard_grid_sort"),
    "subset_object_db_for_pca": ("src.workflows.pca", "subset_object_db_for_pca"),
    "summarize_ablation_effects": ("src.workflows.simca_selection_utils", "summarize_ablation_effects"),
    "summarize_cv_calibration": ("src.workflows.simca", "summarize_cv_calibration"),
    "summarize_duplicated_candidate_review": ("src.workflows.simca_robustness", "summarize_duplicated_candidate_review"),
    "summarize_final_selection": ("src.workflows.simca_final_selection", "summarize_final_selection"),
    "summarize_grouped_decisions": ("src.workflows.simca_grid_evaluation", "summarize_grouped_decisions"),
    "summarize_matrix_output": ("src.workflows.matrix_preprocessing", "summarize_matrix_output"),
    "summarize_metric_stability": ("src.workflows.simca_selection_utils", "summarize_metric_stability"),
    "summarize_mixture_outputs": ("src.workflows.simca_mixture", "summarize_mixture_outputs"),
    "summarize_parameter_tendencies": ("src.workflows.simca_selection_utils", "summarize_parameter_tendencies"),
    "summarize_pca_stability": ("src.workflows.pca", "summarize_pca_stability"),
    "summarize_preprocessing_output": ("src.workflows.matrix_preprocessing", "summarize_preprocessing_output"),
    "summarize_pure_test_outputs": ("src.workflows.simca_pure_test", "summarize_pure_test_outputs"),
    "summarize_random_state_stability_metrics": ("src.workflows.simca_robustness", "summarize_random_state_stability_metrics"),
    "TABLE_KIND_BY_FILE_NAME": ("src.workflows.simca_tables", "TABLE_KIND_BY_FILE_NAME"),
    "TABLE_KIND_BY_FILE_SUFFIX": ("src.workflows.simca_tables", "TABLE_KIND_BY_FILE_SUFFIX"),
    "three_way_extra_group_cols": ("src.workflows.simca_pure_test", "three_way_extra_group_cols"),
    "trace_ratio_by_group": ("src.workflows.pca", "trace_ratio_by_group"),
    "train_projection_shift_by_label": ("src.workflows.pca", "train_projection_shift_by_label"),
    "uses_sg": ("src.workflows.simca", "uses_sg"),
    "valid_sg_parameter_pairs": ("src.workflows.simca", "valid_sg_parameter_pairs"),
    "validate_exhaustive_grid_inputs": ("src.workflows.simca_grid_evaluation", "validate_exhaustive_grid_inputs"),
    "validate_final_selection_contract": ("src.workflows.simca_final_selection", "validate_final_selection_contract"),
    "validate_final_selection_guardrails": ("src.workflows.simca_final_selection", "validate_final_selection_guardrails"),
    "validate_mixture_guardrails": ("src.workflows.simca_mixture", "validate_mixture_guardrails"),
    "validate_mixture_outputs": ("src.workflows.simca_mixture", "validate_mixture_outputs"),
    "validate_pca_artifact_review": ("src.workflows.pca_selection", "validate_pca_artifact_review"),
    "validate_pca_preprocessing_shortlist": ("src.workflows.pca_selection", "validate_pca_preprocessing_shortlist"),
    "validate_pure_test_guardrails": ("src.workflows.simca_pure_test", "validate_pure_test_guardrails"),
    "validate_pure_test_outputs": ("src.workflows.simca_pure_test", "validate_pure_test_outputs"),
    "validate_qc_review_closure": ("src.workflows.quality_check", "validate_qc_review_closure"),
    "validate_required_columns": ("src.workflows.matrix_preprocessing", "validate_required_columns"),
    "validate_simca_candidate_contract": ("src.workflows.simca_candidates", "validate_simca_candidate_contract"),
    "validate_simca_candidates_match_pca_preprocessing": ("src.workflows.simca_candidates", "validate_simca_candidates_match_pca_preprocessing"),
    "validate_simca_evaluation_contract": ("src.workflows.simca_candidates", "validate_simca_evaluation_contract"),
    "validate_simca_robustness_inputs": ("src.workflows.simca_robustness", "validate_simca_robustness_inputs"),
    "validate_simca_selection_tracks": ("src.workflows.simca_candidates", "validate_simca_selection_tracks"),
    "validate_simca_table_columns": ("src.workflows.simca_candidates", "validate_simca_table_columns"),
    "validate_upstream_tables_are_pre_test": ("src.workflows.simca_pure_test", "validate_upstream_tables_are_pre_test"),
    "write_simca_table": ("src.workflows.simca_tables", "write_simca_table"),
}

__all__ = sorted(_PUBLIC_API)


def __getattr__(name: str) -> Any:
    """Import a public workflow attribute only when it is requested."""
    try:
        module_name, attribute_name = _PUBLIC_API[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
