from src.spectra.preprocessing_configs import normalize_preprocessing_configs
from src.spectra.preprocessing import SpectralPreprocessor
from src.spectra.band_selection import wavelength_selection_summary, select_wavelength_range_from_database